import type { Metadata } from "next";

import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';
import { StyledRoot } from './styledRoot';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body >
        <AppRouterCacheProvider>
          <StyledRoot>{children}</StyledRoot>
        </AppRouterCacheProvider>
      </body>
       
      {/* </body> */}
    </html>
  );
}
